"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ProductService_1 = require("./ProductService");
var Products_1 = require("./Products");
var _productService = new ProductService_1.ProductService();
var result;
result = _productService.getProducts();
result = _productService.getById(2);
var p = new Products_1.Product();
p.id = 3;
p.name = "Iphone 6";
p.price = 400;
p.category = "telefon";
_productService.saveProduct(p);
_productService.deleteProduct(result);
console.log(result);
